# Use the base image built by main Dockerfile
FROM samurai:latest

# Set the working directory
WORKDIR /app

# Ensure pip is installed
RUN apt-get update && apt-get install -y python3-pip

# Install the Python packages required by the validation scripts
RUN pip3 install --no-cache-dir numpy xarray

# Make the validation script executable
RUN chmod +x /app/samurai/ncar_scripts/validation/beltrami/bel_val_nc.py

# Set the CMD to run the validation script
CMD ["python3", "/app/samurai/ncar_scripts/validation/beltrami/bel_val_nc.py", "/app/samurai/ncar_scripts/validation/beltrami/samurai_XYZ_wind_analysis_ref.nc", "/app/samurai/build/release/bin/samurai_XYZ_wind_analysis.nc"]