// Wrapper around the trdp generated data structures to
// allow for parameter overrides

#ifndef Args.h
#define Args.h

#include "Params.hh" // generated by trdp_gen
#include <unordered_set>

class Args {
  
 public:
  QHash<QString, QString> parseArgs(int argc, char *argv[]);
  
 private:
  QHash<QString, QString>  params_to_hash();

  Params params;
}

#endif // Args.h
