// Wrapper around the trdp generated data structures to
// allow for parameter overrides

#ifndef ARGS_H
#define ARGS_H

#include "Params.hh" // generated by trdp_gen
#include <unordered_map>
#include <string>

class Args {
  
 public:
  
  bool parseArgs(int argc, char *argv[]);
  bool paramsToHash(std::unordered_map<std::string, std::string> *configHash);
    
 private:
  
  std::unordered_map<std::string, std::string>  params_to_hash();

  Params params;
};

#endif // ARGS_H
