name: Samurai CPU test with Beltrami

on:
  workflow_dispatch:
    branches: 
      - "main"
      - "thermo_asap"
  push:
    branches: 
      - "main"
      - "thermo_asap"
  pull_request:
    branches: 
      - "main"
      - "thermo_asap"
      
jobs:
  docker-build-and-test:
    name: Build and Test - ${{ matrix.dockerfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dockerfile:
          - Dockerfile
          - Dockerfile.coverage 
    steps:
    - name: Checkout code from a pull request or push
      uses: actions/checkout@v3

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Build Docker image
      run: docker build -f docker/${{ matrix.dockerfile }} -t samurai .

    - name: Running the Docker image for Beltrami case
      # only run this if we are not running codecoverage tests
      if: matrix.dockerfile != 'Dockerfile'
      run: 
        docker run --name test-container -t samurai
        docker exec test-container python3 /app/samurai/ncar_scripts/validation/beltrami/bel_val_nc.py /app/samurai/ncar_scripts/validation/beltrami/samurai_XYZ_wind_analysis_ref.nc /app/samurai/build/release/bin/samurai_XYZ_wind_analysis.nc


    - name: Validation - check RMSE values of Beltrami output
      if: matrix.dockerfile != 'Dockerfile'
      run: docker run --name test-container -t samurai make test

    - name: Run coverage tests in container
      if: matrix.dockerfile == 'Dockerfile.coverage'
      run: docker run --name test-container -t samurai make coverage

    - name: Copy coverage from container
      if: matrix.dockerfile == 'Dockerfile.coverage'
      run: docker cp test-container:/app/samurai/build/coverage.info .

    - name: Upload coverage reports to Codecov
      if: matrix.dockerfile == 'Dockerfile.coverage'
      uses: codecov/codecov-action@v4
      with:
        files: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
