name: Samurai CPU CI with Beltrami

on:
  workflow_dispatch:
    branches: 
      - "main"
      - "thermo_asap"
  push:
    branches: 
      - "main"
      - "thermo_asap"
  pull_request:
    branches: 
      - "main"
      - "thermo_asap"
      
jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from a pull request or push
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t samurai:latest .

    - name: Running the Docker image for Beltrami case
      run: |
        docker run -d --name test-container samurai:latest

    - name: Save Docker image to cache
      uses: actions/cache@v3
      with:
        path: /tmp/samurai.tar
        key: ${{ runner.os }}-samurai-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-samurai-
  
    - name: Save Docker image
      run: docker save -o /tmp/samurai.tar samurai:latest

  validation:
    name: Validation
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
    - name: Checkout code from a pull request or push
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Restore Docker image from cache
      uses: actions/cache@v3
      with:
        path: /tmp/samurai.tar
        key: ${{ runner.os }}-samurai-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-samurai-

    - name: Load Docker image
      run: docker load -i /tmp/samurai.tar

    - name: Build and run validation container
      run: |
        docker build -f docker/Dockerfile.validation -t samurai-validation .
        docker run --name test-container-validation --volumes-from test-container samurai-validation

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from a pull request or push
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Build Docker image
      run: docker build -f docker/Dockerfile.coverage -t samurai .

    - name: Run coverage tests in container
      run: docker run --name test-container -t samurai make coverage

    - name: Copy coverage from container
      run: docker cp test-container:/app/samurai/build/coverage.info .

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}