name: Samurai CPU test with Beltrami

on:
  workflow_dispatch:
    branches: [ "main" ]
  push:
    branches: [ "derecho_ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build-and-test:
    name: Build and Test - ${{ matrix.dockerfile }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dockerfile:
          - Dockerfile
          - Dockerfile.coverage 
    steps:
    - name: Checkout code from a pull request or push
      uses: actions/checkout@v3

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Submit the job to the derecho
      run: qcmd -q develop -l select=1:ncpus=128:ompthreads=128:mem=230GB -A NEOL0013 -l walltime=02:30:00 -- "ncar_scripts/derecho_cpu_submit.sh"

